[package]
name = "as-types"
version = "0.1.0"
edition = "2021"

[dependencies]
kbs-types = { git = "https://github.com/chendave/kbs-types.git", branch = "demo1.0_backup" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
